/**
 * As 2048 palavras de que um código de recuperação é sorteado.
 *
 * Tiradas do próprio banco de frases em português do produto, que é de onde
 * vinha a alternativa de qualquer jeito: são palavras que alguém que usa o
 * PERSEUSS já digitou treinando, sem acento e entre quatro e oito letras.
 *
 * Duas propriedades foram impostas na geração, e as duas existem pra quem está
 * copiando isto à mão num dia ruim:
 *
 *   - **Sem acento e sem cedilha.** O código é lido em voz alta e digitado num
 *     teclado que pode não ser o de casa. Uma palavra que precise de tecla
 *     morta é uma palavra que alguém vai errar.
 *   - **Prefixo de quatro letras único.** Duas palavras da lista nunca começam
 *     igual, então errar o fim de uma ainda deixa ela identificável. É a mesma
 *     escolha que a lista BIP-39 faz, pelo mesmo motivo.
 *
 * 2048 palavras são 11 bits cada; seis delas, 66 bits. Não é segredo escolhido
 * por humano — não tem data de aniversário dentro — então resiste a dicionário
 * sem precisar do custo de um KDF por trás.
 *
 * Gerado a partir de `packages/corpus/src/data/*-pt-br.ts`. A lista pode ser
 * regerada à vontade: um código já emitido continua valendo, porque o que o
 * banco guarda é o hash das palavras que a pessoa digita, e não um índice nesta
 * lista.
 */
export const RECOVERY_WORDS: readonly string[] = [
  'aardvark', 'abacaxi', 'abaixo', 'abajur', 'abalada', 'abanava', 'abarca',
  'abate', 'abdomen', 'abelhas', 'aberta', 'ablativo', 'aborrece', 'abram',
  'abre', 'abrir', 'abrupta', 'absoluta', 'abstrata', 'absurdas', 'acabei',
  'academia', 'acalmam', 'acampar', 'acao', 'acaso', 'aceitar', 'acelerar',
  'acender', 'acertar', 'acesso', 'achar', 'achei', 'acho', 'acidente',
  'acima', 'aclamado', 'acode', 'acoes', 'acontece', 'acordo', 'acredito',
  'actinio', 'acucar', 'acumulo', 'acusacao', 'adaptado', 'adcione',
  'adesao', 'adiada', 'adiciono', 'adjetivo', 'admirava', 'adora',
  'adotivo', 'adquire', 'adultos', 'advertiu', 'advogado', 'aerea',
  'aeromoco', 'afastar', 'afeicoes', 'afetivas', 'afiar', 'afinador',
  'afirma', 'afogar', 'agarrou', 'agendado', 'agindo', 'agir', 'agitava',
  'agora', 'agosto', 'agradar', 'aguas', 'aguentar', 'aguia', 'agulha',
  'ainda', 'aipo', 'ajeita', 'ajudar', 'ajustado', 'alarme', 'albatroz',
  'albergue', 'alcancar', 'aldeia', 'alegria', 'alemao', 'alfabeto',
  'algas', 'algo', 'algumas', 'alheia', 'aliar', 'alimenta', 'alivio',
  'alma', 'almoco', 'alta', 'alterar', 'alto', 'altura', 'aluguel',
  'aluminio', 'alunos', 'amado', 'amanha', 'amarelo', 'amava', 'ambiente',
  'ambos', 'ameaca', 'amem', 'amido', 'amigo', 'amizade', 'amor', 'amou',
  'amplas', 'analisa', 'andar', 'anedotas', 'angulos', 'anidrido',
  'animais', 'anistia', 'anjo', 'anorexia', 'anos', 'anotar', 'ansiosa',
  'antes', 'antigo', 'antraz', 'anuncio', 'anzol', 'apagar', 'apanhado',
  'aparelho', 'apegou', 'apelido', 'apenas', 'apertar', 'apesar', 'apito',
  'aplaudiu', 'aplicada', 'apodrece', 'apoio', 'aposta', 'apraz',
  'aprender', 'aprovou', 'aquele', 'aqui', 'arabe', 'aranhas', 'arbitro',
  'arco', 'ardente', 'areia', 'armario', 'aroma', 'arquivos', 'arranjar',
  'arroz', 'arrumar', 'arte', 'artigo', 'arvores', 'asas', 'aspecto',
  'aspirina', 'assado', 'assento', 'assim', 'assolada', 'assunto',
  'atacada', 'atalho', 'ataque', 'atentos', 'ateu', 'atilhos', 'atingiu',
  'atirar', 'atitude', 'ativos', 'atletas', 'atomos', 'ator', 'atos',
  'atras', 'atual', 'atulhada', 'auge', 'aula', 'aumentou', 'aureola',
  'ausencia', 'autor', 'auxilia', 'avanco', 'avela', 'avenida', 'avestruz',
  'aviacao', 'avidos', 'avise', 'avos', 'azeite', 'azuis', 'azul', 'bafo',
  'bagagem', 'baile', 'bairro', 'baixo', 'balas', 'balde', 'baleias',
  'bambu', 'banana', 'banco', 'bandidos', 'banho', 'baralho', 'barba',
  'barco', 'bares', 'barriga', 'barulho', 'baseball', 'basico', 'bastante',
  'batatas', 'bateu', 'batia', 'baus', 'beba', 'beber', 'bebida', 'bebo',
  'beijo', 'beira', 'beisebol', 'bela', 'beleza', 'belgas', 'belo', 'bens',
  'berbere', 'betao', 'bico', 'bigorna', 'bijecao', 'bilhoes', 'biologia',
  'bispo', 'blog', 'bloqueio', 'boas', 'bobagem', 'bobeira', 'boca', 'bola',
  'bolo', 'bolsa', 'bondade', 'boneco', 'bonita', 'bons', 'bordou',
  'borracha', 'bosque', 'botas', 'boteco', 'botoes', 'braco', 'branco',
  'brava', 'breve', 'briga', 'brilha', 'brinquei', 'bronze', 'bruxas',
  'buraco', 'busca', 'bussola', 'cabeca', 'cabine', 'cabo', 'caca',
  'cachorro', 'cada', 'cadeira', 'caem', 'caes', 'caido', 'caipira', 'cair',
  'caiu', 'caixa', 'calado', 'calcula', 'calhas', 'calmo', 'calor', 'calvo',
  'cama', 'cameras', 'caminho', 'campo', 'cancao', 'caneta', 'canina',
  'cansado', 'cantar', 'caozinho', 'capaz', 'capela', 'capitao', 'capturar',
  'caquis', 'cara', 'carbono', 'cardiaco', 'carece', 'carga', 'carinho',
  'carne', 'caro', 'carro', 'carta', 'carvao', 'casa', 'casco', 'casemos',
  'caso', 'castelo', 'catando', 'catedral', 'cauda', 'causa', 'cavalo',
  'caverna', 'cavidade', 'cedeu', 'cedinho', 'cedo', 'cedros', 'cegos',
  'cegueira', 'ceia', 'celebrar', 'celular', 'cenario', 'cento', 'cerca',
  'cerebro', 'cerradas', 'certeza', 'cerveja', 'cesta', 'chacara', 'chama',
  'chances', 'chao', 'chapeu', 'charuto', 'chata', 'chave', 'checando',
  'chefe', 'chegar', 'cheia', 'chiclete', 'chifre', 'chines', 'chique',
  'chocado', 'chorar', 'chover', 'chumbo', 'chutei', 'chuva', 'cidade',
  'ciente', 'cilada', 'cima', 'cimento', 'cinco', 'cinema', 'cinzas',
  'circulo', 'cirurgia', 'cisne', 'cita', 'ciumes', 'civil', 'claro',
  'classe', 'claustro', 'clientes', 'clima', 'clinica', 'clube', 'coalas',
  'coaxo', 'coberta', 'cobra', 'cochilo', 'cocuruto', 'codigo', 'codons',
  'coelhos', 'coisa', 'cola', 'colchao', 'colegas', 'colher', 'colina',
  'colmeia', 'colocar', 'comandar', 'combina', 'comecou', 'comida', 'como',
  'comprar', 'comum', 'concerto', 'conduta', 'conexoes', 'conforme',
  'conheco', 'conjunto', 'conosco', 'consegui', 'conta', 'conversa',
  'copias', 'copo', 'coragem', 'corda', 'cores', 'coristas', 'cornos',
  'corpo', 'correndo', 'cortar', 'cosseno', 'costuma', 'coveiro', 'coxa',
  'cozinha', 'cravar', 'credito', 'creme', 'crer', 'crescer', 'criancas',
  'criou', 'crise', 'critica', 'cromio', 'croquete', 'cruzados', 'cuidado',
  'cuja', 'cujo', 'culpa', 'cultura', 'cumes', 'cumprido', 'cunhado',
  'cupom', 'cura', 'curiosos', 'curso', 'curta', 'custa', 'cutuco', 'dadas',
  'dados', 'dali', 'dama', 'dancar', 'dando', 'daninho', 'dano', 'daqui',
  'dara', 'darei', 'daria', 'data', 'dativo', 'debaixo', 'decada',
  'decente', 'decisoes', 'declarou', 'decorado', 'dedicou', 'dedos',
  'defeitos', 'definido', 'defunto', 'deitar', 'deixou', 'dela', 'dele',
  'delito', 'demais', 'demitida', 'demorou', 'densa', 'dentro', 'depende',
  'depois', 'deprime', 'deram', 'deriva', 'derreter', 'desastre',
  'desculpa', 'desde', 'desejo', 'desfeito', 'desistir', 'desjejum',
  'deslizar', 'desmaiei', 'despedir', 'desse', 'desta', 'desvio',
  'detalhes', 'deter', 'detido', 'detras', 'devagar', 'deve', 'devido',
  'devo', 'dezembro', 'dialetos', 'diante', 'diario', 'dias', 'dieta',
  'dificeis', 'diga', 'digestao', 'digital', 'digno', 'digo', 'dinheiro',
  'dioxido', 'direito', 'dirigir', 'discurso', 'dispoe', 'disse',
  'distante', 'ditadura', 'dito', 'diversos', 'divida', 'divorcio',
  'divulgou', 'dizer', 'doacao', 'doador', 'doar', 'dobro', 'doce', 'docil',
  'doidinho', 'dois', 'dolares', 'doloroso', 'domingo', 'dona', 'donos',
  'doou', 'dores', 'dormir', 'dorso', 'doses', 'dourado', 'doutor', 'doze',
  'dracmas', 'dragoes', 'duas', 'duma', 'dupla', 'durante', 'durou',
  'duvida', 'duzentos', 'eczema', 'edicoes', 'edificio', 'educacao',
  'efeitos', 'eficaz', 'egipcios', 'egua', 'elas', 'elefante', 'elegante',
  'eles', 'eletrica', 'elevador', 'elfo', 'elogios', 'embaixo', 'embora',
  'emenda', 'emerge', 'emissoes', 'emitia', 'emocoes', 'empate', 'empilho',
  'empresa', 'encanta', 'encerram', 'enche', 'encontro', 'endereco',
  'energia', 'enfeitar', 'enganou', 'enguia', 'enigma', 'enlatada',
  'enologo', 'enorme', 'enquanto', 'enredo', 'ensaboo', 'entanto',
  'entender', 'entre', 'enviar', 'envolver', 'eolica', 'epoca', 'equador',
  'equipe', 'eram', 'eras', 'ergue', 'errado', 'erros', 'ervilha',
  'escadas', 'escola', 'escrever', 'escudo', 'esforco', 'esfregou',
  'eslavos', 'esmola', 'espanhol', 'espero', 'espirito', 'esposa',
  'esqueci', 'essa', 'esse', 'esta', 'este', 'estilo', 'estou', 'estrada',
  'estudar', 'esvazia', 'etapa', 'eterna', 'euros', 'evento', 'evitar',
  'evolucao', 'exagerar', 'exalam', 'exames', 'exatas', 'exausto', 'exceto',
  'executou', 'exemplo', 'exerciam', 'exibia', 'exige', 'exilio', 'existem',
  'exito', 'expira', 'explicou', 'expostos', 'exprimiu', 'expulso',
  'exterior', 'extincao', 'extrema', 'fabrica', 'faca', 'face', 'faco',
  'fada', 'fadiga', 'fagulha', 'falar', 'falei', 'falhar', 'falo', 'falsa',
  'falta', 'fama', 'familias', 'famoso', 'fantasma', 'farao', 'farei',
  'faria', 'farta', 'fascina', 'fase', 'fatais', 'fatias', 'fato', 'favas',
  'favor', 'fazer', 'fazia', 'febre', 'fechou', 'feijao', 'feio', 'feira',
  'feito', 'feixe', 'feliz', 'femea', 'fenda', 'fenol', 'fera', 'ferias',
  'feroz', 'ferro', 'fervor', 'festa', 'fica', 'ficcao', 'ficou', 'fiel',
  'figuras', 'fila', 'filhos', 'filme', 'filosofo', 'filtram', 'final',
  'fingindo', 'fino', 'fins', 'fiquei', 'firewall', 'firme', 'fisguei',
  'fisica', 'fita', 'fixo', 'fizeram', 'flama', 'flauta', 'flecha',
  'flocos', 'floresta', 'fluente', 'flui', 'fluvial', 'fluxo', 'focar',
  'focinho', 'fogao', 'fogo', 'foguetes', 'folga', 'folhas', 'fome',
  'fomos', 'fones', 'fonte', 'foram', 'forca', 'forem', 'forma', 'forno',
  'forte', 'fosforo', 'fosse', 'foto', 'fraco', 'francesa', 'fraqueza',
  'frase', 'frente', 'fresca', 'fria', 'frio', 'fritas', 'frustrar',
  'frutos', 'ftalico', 'fugiu', 'fujam', 'fuligem', 'fumar', 'funcao',
  'fundo', 'fungos', 'funil', 'furacao', 'furioso', 'fusao', 'fusca',
  'futebol', 'futuro', 'fuzil', 'gabinete', 'gado', 'gaivotas', 'galaxia',
  'galho', 'galinhas', 'galo', 'gama', 'games', 'ganhar', 'garagem',
  'garcons', 'garfos', 'garganta', 'garoto', 'garrafa', 'gases', 'gasolina',
  'gastou', 'gata', 'gato', 'gauleses', 'gaveta', 'gelado', 'gelo',
  'gemada', 'gemeos', 'gemidos', 'genero', 'gengibre', 'genio', 'gente',
  'geologia', 'geral', 'gerencia', 'gesso', 'gestual', 'gigante', 'girafa',
  'girias', 'glacial', 'global', 'gloria', 'goleiro', 'golpe', 'gordo',
  'gostaria', 'gota', 'gotica', 'graca', 'grado', 'grafico', 'gramas',
  'grande', 'grato', 'graus', 'gravura', 'grilo', 'gritei', 'grosso',
  'grudado', 'grupo', 'guarda', 'guiam', 'guinou', 'guitarra', 'gumes',
  'habito', 'haicais', 'haja', 'harmonia', 'hasta', 'haver', 'havia',
  'hebraico', 'heranca', 'hesterno', 'higiene', 'hobby', 'hoje', 'holandes',
  'homem', 'honrado', 'horas', 'horrivel', 'hospedar', 'hotel', 'houve',
  'humanos', 'humilde', 'hungaro', 'iamos', 'idade', 'ideal', 'ideia',
  'identica', 'idiomas', 'idosos', 'ienes', 'ignorado', 'igual', 'ilegivel',
  'ilha', 'ilumina', 'ilusao', 'imagem', 'imbecis', 'imensos', 'imersivo',
  'imita', 'impacto', 'imperios', 'implorei', 'importa', 'imprime',
  'incapaz', 'incendio', 'inchados', 'incitar', 'incluem', 'incrivel',
  'indice', 'indo', 'infancia', 'inferior', 'inflavel', 'informar',
  'infusoes', 'inglesa', 'ingresso', 'inicio', 'inimigos', 'injusto',
  'inocente', 'insetos', 'inspirou', 'instante', 'insulto', 'inteira',
  'intimo', 'inumeras', 'inutil', 'invadir', 'inverno', 'ioga', 'irao',
  'irei', 'irem', 'iria', 'iris', 'irmaos', 'ironia', 'irritado', 'isolada',
  'isotopo', 'isso', 'isto', 'italiano', 'jamais', 'janela', 'jantar',
  'japonesa', 'jaqueta', 'jardim', 'jasmim', 'javali', 'jaziam', 'jazz',
  'jeito', 'jogar', 'jogo', 'joguei', 'jornal', 'jovem', 'juiz', 'julgar',
  'julho', 'junho', 'junto', 'jurar', 'jurem', 'justica', 'labios', 'lado',
  'ladrao', 'lagarta', 'lago', 'lagrimas', 'lambeu', 'lampadas', 'lancada',
  'lanterna', 'lapis', 'laptop', 'laranja', 'lareira', 'largura', 'lasanha',
  'lateral', 'latim', 'lavar', 'lavo', 'lealdade', 'leao', 'lebre', 'legal',
  'legendas', 'legou', 'legumes', 'leia', 'leio', 'leis', 'leite', 'lembro',
  'leme', 'lenco', 'lendo', 'lenha', 'lenta', 'leque', 'lerdo', 'leria',
  'lermos', 'lesma', 'leste', 'letras', 'levar', 'leve', 'levou', 'lhes',
  'liberado', 'libras', 'licao', 'licenca', 'licoes', 'lida', 'lideres',
  'lido', 'ligar', 'ligo', 'ligue', 'limpar', 'linda', 'lingua', 'linhas',
  'liquido', 'lirios', 'lisa', 'lista', 'literal', 'litros', 'livro',
  'lixado', 'lixo', 'lobo', 'local', 'logica', 'logo', 'loiros', 'loja',
  'longe', 'loucura', 'louros', 'luar', 'lucro', 'lugar', 'lulas',
  'luminosa', 'luta', 'luxo', 'luxuosos', 'luzes', 'macas', 'machucou',
  'macia', 'madeira', 'madrasta', 'madura', 'magia', 'magoa', 'magra',
  'mahjong', 'mail', 'maior', 'mais', 'mala', 'maldade', 'males', 'maligno',
  'maluco', 'mandou', 'maneira', 'manga', 'manha', 'manter', 'maos', 'mapa',
  'maquina', 'maratona', 'marco', 'margem', 'marido', 'marrom', 'martelo',
  'mascaras', 'massa', 'mastro', 'mata', 'materia', 'mato', 'maus',
  'maximo', 'meados', 'mecanica', 'mede', 'medico', 'medo', 'medusas',
  'meia', 'meigo', 'meio', 'melancia', 'melhor', 'melodia', 'membros',
  'mendigos', 'menino', 'menos', 'mensagem', 'mente', 'mera', 'mercado',
  'merece', 'mergulho', 'merito', 'mesa', 'meses', 'mesmo', 'mestre',
  'metade', 'metodos', 'metros', 'meus', 'midias', 'migracao', 'milenio',
  'milhoes', 'militar', 'mimimi', 'minerais', 'minha', 'minimo', 'minutos',
  'mirou', 'mirtilo', 'missao', 'misterio', 'mito', 'mocao', 'mocidade',
  'moda', 'modelo', 'modo', 'modula', 'moedas', 'moinho', 'molecula',
  'molho', 'momento', 'mona', 'monstro', 'montanha', 'morar', 'morcego',
  'mordeu', 'moro', 'morre', 'mosaica', 'moscas', 'mostra', 'motivos',
  'motores', 'movendo', 'muares', 'mudar', 'mudei', 'mudou', 'muito',
  'mula', 'mulher', 'multidao', 'mumia', 'mundo', 'muralha', 'murcham',
  'muro', 'muscular', 'museu', 'musicas', 'mute', 'nacao', 'nacional',
  'nacoes', 'nada', 'nado', 'namorada', 'naquela', 'narcose', 'nariz',
  'narracao', 'nasceu', 'natal', 'natural', 'navega', 'navio', 'neblina',
  'negativo', 'negocio', 'negros', 'nela', 'nele', 'nenhum', 'nervoso',
  'nesse', 'neste', 'neta', 'netinho', 'neto', 'nevar', 'neve', 'ninguem',
  'ninho', 'nisso', 'nobre', 'nocivos', 'noite', 'noivado', 'nojentos',
  'nojo', 'nome', 'nora', 'normal', 'norte', 'nosso', 'notas', 'notei',
  'noticias', 'noturno', 'nova', 'nove', 'novilha', 'novo', 'nozes',
  'numeros', 'nunca', 'obedecer', 'objetivo', 'obras', 'obrigado',
  'obscura', 'observou', 'obstruir', 'obter', 'obtido', 'ocaso', 'oceano',
  'ocorre', 'ocultar', 'ocupado', 'odeia', 'odor', 'oeste', 'ofegando',
  'ofendido', 'ofereceu', 'oficina', 'oitenta', 'oito', 'oleo', 'olhar',
  'olhei', 'olhos', 'olimpica', 'ombro', 'omeletes', 'ondas', 'onde',
  'onibus', 'online', 'ontem', 'onze', 'opcoes', 'opiniao', 'opoem',
  'oposto', 'orador', 'ordenou', 'orelhas', 'orfa', 'orgaos', 'orgulho',
  'orientam', 'origem', 'orou', 'orvalho', 'osgas', 'ossos', 'otimo',
  'ouro', 'ousadia', 'outono', 'outro', 'outubro', 'ouve', 'ouvir',
  'ovelhas', 'ovos', 'oxigenio', 'paciente', 'pacote', 'padrinho', 'paella',
  'pagar', 'pagens', 'paginas', 'paguei', 'pais', 'paixoes', 'paizinho',
  'palavras', 'paletes', 'palida', 'palpebra', 'pancada', 'pandora',
  'panela', 'panico', 'panorama', 'papagaio', 'papel', 'papiro', 'para',
  'parcial', 'parece', 'parou', 'parque', 'parte', 'parvos', 'passado',
  'pastor', 'patas', 'paternal', 'patins', 'patria', 'pausa', 'pazes',
  'pecas', 'peco', 'pedacos', 'pede', 'pediu', 'pedra', 'pegar', 'pegou',
  'peguei', 'peito', 'peixe', 'pela', 'pele', 'pelo', 'peludas', 'pena',
  'pendurar', 'penhasco', 'penico', 'pensar', 'pente', 'pequeno', 'percebi',
  'perdi', 'perfeito', 'perigo', 'permite', 'pernas', 'perolas', 'perplexo',
  'persa', 'perto', 'peru', 'pesa', 'pescoco', 'peseta', 'peso', 'pesquisa',
  'pessoas', 'petroleo', 'piada', 'piano', 'picada', 'pico', 'piedoso',
  'pilhas', 'piloto', 'pinca', 'pintura', 'pior', 'piramide', 'pirei',
  'piscina', 'pisei', 'pizza', 'placas', 'plano', 'plastico', 'plateia',
  'plena', 'plumas', 'pneu', 'pobre', 'pode', 'podia', 'podre', 'poema',
  'poesia', 'poeta', 'pois', 'policia', 'polo', 'poluicao', 'polvora',
  'pombos', 'poneis', 'ponha', 'ponto', 'popular', 'porcos', 'porem',
  'poriamos', 'porque', 'porta', 'positivo', 'posso', 'posto', 'potencia',
  'pouco', 'poupar', 'pousou', 'povo', 'praca', 'prado', 'praga', 'praia',
  'prato', 'prazer', 'preciso', 'predio', 'preencha', 'prefiro', 'preguei',
  'prejuizo', 'premio', 'prende', 'preocupo', 'preparar', 'presente',
  'preto', 'previsao', 'primeira', 'principe', 'proa', 'problema',
  'processo', 'produz', 'profunda', 'programa', 'projeto', 'prometeu',
  'pronto', 'propria', 'protecao', 'prova', 'proxima', 'prudente',
  'publica', 'pudesse', 'pular', 'pulga', 'pulinho', 'punhos', 'puniu',
  'pura', 'pure', 'puseram', 'puxadas', 'quadro', 'quais', 'qualquer',
  'quando', 'quao', 'quarto', 'quase', 'quatro', 'quebrou', 'queda',
  'queijo', 'quem', 'quente', 'quero', 'questoes', 'quilos', 'quimica',
  'quinze', 'quiser', 'rabo', 'radio', 'radonio', 'rainha', 'raios',
  'raiva', 'ramos', 'rampa', 'rapazes', 'rapido', 'raposa', 'raptor',
  'raras', 'raros', 'rato', 'razoes', 'reaberto', 'reacao', 'reagir',
  'reais', 'realizar', 'reanimar', 'rebanho', 'recebeu', 'recifes',
  'reclama', 'recompor', 'recusou', 'redator', 'rede', 'redor', 'reduzir',
  'refeicao', 'refletir', 'reforma', 'regiao', 'regras', 'regua', 'reina',
  'relacoes', 'religiao', 'relogio', 'remedio', 'remos', 'renovar', 'rente',
  'reparou', 'repente', 'repinte', 'replicou', 'repouso', 'represa',
  'requer', 'reservar', 'resgate', 'reside', 'resolver', 'respeito',
  'restinho', 'resumo', 'reta', 'reto', 'retrato', 'reuniao', 'revela',
  'revista', 'revolta', 'riacho', 'ribeiro', 'rica', 'rico', 'rigido',
  'rindo', 'riqueza', 'riscos', 'riso', 'ritmo', 'ritos', 'robos', 'rocha',
  'rock', 'roda', 'roer', 'romance', 'root', 'rosa', 'rosto', 'rotina',
  'roubou', 'rouco', 'roupas', 'rouxinol', 'ruas', 'rublos', 'rude',
  'ruidos', 'ruim', 'rumo', 'russo', 'sabado', 'saber', 'sabia', 'saboreie',
  'sacos', 'sadismo', 'saem', 'sagrado', 'saia', 'saiba', 'saido', 'saimos',
  'saindo', 'saio', 'sair', 'saisse', 'saiu', 'sala', 'salgados',
  'salsicha', 'saltos', 'salvar', 'sangram', 'saos', 'sapatos', 'sapos',
  'sarampo', 'saude', 'seca', 'secou', 'secreto', 'seculos', 'seda', 'sede',
  'segredo', 'seguinte', 'seis', 'seja', 'seletiva', 'selos', 'selvagem',
  'semana', 'sementes', 'sempre', 'sendo', 'senhor', 'senso', 'sentido',
  'separou', 'sequer', 'sera', 'seres', 'seria', 'serpeava', 'serras',
  'servico', 'sessenta', 'sesta', 'sete', 'seus', 'shopping', 'show',
  'sido', 'sigma', 'signos', 'silabas', 'silencio', 'simples', 'sirvo',
  'sistema', 'sites', 'sitio', 'situada', 'skates', 'soava', 'sobe',
  'sobre', 'sociais', 'socorro', 'sofre', 'soja', 'solar', 'solteiro',
  'solucoes', 'soma', 'sombra', 'somente', 'somos', 'soneca', 'sonho',
  'sono', 'sons', 'soprando', 'sorriso', 'sorte', 'sorvete', 'soubesse',
  'sozinho', 'suas', 'suave', 'subiu', 'suborno', 'sucesso', 'suco',
  'sueter', 'sufixo', 'sufocado', 'sugeriu', 'sujas', 'sujeito', 'sujo',
  'suma', 'sumiu', 'superar', 'suplicou', 'supostas', 'suprema', 'surdos',
  'surgiu', 'surpresa', 'sushi', 'suspeito', 'sussurro', 'sutil', 'tabaco',
  'taca', 'tachado', 'taco', 'tais', 'talento', 'talisma', 'talvez',
  'tamanho', 'tampa', 'tangente', 'tanque', 'tanto', 'tapetes', 'tapumes',
  'tarde', 'tarefas', 'tatico', 'tatuagem', 'tava', 'taxi', 'teatro',
  'tecendo', 'tecido', 'teclado', 'tecnica', 'teia', 'tela', 'telefone',
  'telhado', 'tema', 'temendo', 'temido', 'temos', 'tempo', 'tendo',
  'tenente', 'tenho', 'tenis', 'tentar', 'teoria', 'tequila', 'tera',
  'terceiro', 'teremos', 'teria', 'terminar', 'terno', 'terra', 'tese',
  'tesouro', 'teste', 'teto', 'teve', 'texto', 'tido', 'tigre', 'timbre',
  'time', 'timido', 'tinha', 'tintas', 'tios', 'tipo', 'tirar', 'tirem',
  'titulos', 'tivesse', 'toca', 'tochas', 'tocou', 'todas', 'todos', 'tola',
  'toldo', 'tolera', 'tolo', 'tomar', 'tombara', 'tomei', 'tomou', 'tonica',
  'tons', 'tonto', 'topo', 'toque', 'torcida', 'torio', 'tornar', 'torque',
  'torre', 'tortura', 'tosse', 'total', 'toucinho', 'touro', 'trabalho',
  'tracado', 'traduzir', 'trafego', 'tragico', 'traje', 'trama', 'transito',
  'trapos', 'tras', 'trata', 'travesso', 'trazer', 'trecho', 'trem',
  'trens', 'trepar', 'tres', 'trevas', 'treze', 'tribunal', 'tricotou',
  'trigo', 'trilha', 'trinta', 'trio', 'triste', 'trocar', 'tronco',
  'tropas', 'trouxe', 'trovao', 'trunfos', 'tudo', 'tufao', 'tulipas',
  'tumulo', 'tunel', 'tupis', 'turba', 'turco', 'turistas', 'turma',
  'turvado', 'uisque', 'ultimas', 'umas', 'umido', 'unhas', 'uniao',
  'unicos', 'unidades', 'uniforme', 'universo', 'uranio', 'urbano',
  'urgencia', 'urina', 'urso', 'usado', 'usam', 'usando', 'usar', 'usavam',
  'useis', 'usem', 'usou', 'uteis', 'util', 'vacas', 'vagas', 'vaguei',
  'vale', 'valha', 'valida', 'valor', 'vamos', 'vanilina', 'vantagem',
  'vapor', 'varanda', 'varias', 'vaso', 'vasto', 'vazia', 'vedar',
  'vedetes', 'veem', 'vegetal', 'veiculo', 'veio', 'veja', 'vejo', 'velas',
  'velho', 'veloz', 'vemos', 'vencer', 'vender', 'venha', 'vento', 'verbo',
  'verdade', 'vergonha', 'vermelho', 'veroes', 'versos', 'vesperas',
  'vestido', 'vezes', 'viagem', 'viajar', 'vibracao', 'vicios', 'vida',
  'video', 'vidro', 'viemos', 'vieram', 'viesse', 'vigiando', 'vikings',
  'vila', 'vimos', 'vinagre', 'vinculos', 'vindo', 'vinganca', 'vinho',
  'vinil', 'vinte', 'violao', 'vira', 'virei', 'virgula', 'virou',
  'virtude', 'visa', 'visita', 'visoes', 'vista', 'vitima', 'vitoria',
  'vitrine', 'viuva', 'viva', 'vive', 'viviam', 'vivo', 'vizinhos',
  'voadores', 'voam', 'voando', 'voava', 'vocativo', 'voce', 'vodca',
  'vogais', 'volta', 'volume', 'vomitou', 'vontade', 'voou', 'votar',
  'votos', 'vulcao', 'weta', 'xadrez', 'xampu', 'xerife', 'xicara', 'yenes',
  'zangada', 'zarpar', 'zebra', 'zero', 'zodiaco'
];
